actors:
  eiji:
    image_url: /images/actors/eiji.jpg
    name: Eiji
    url: https://twitter.com/shinodogg
  tatsuro:
    image_url: /images/actors/tatsuro.jpg
    name: Tatsuro
    url: http://twitter.com/t2hnd
author: eiji
description: Search & Discoveryãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ ã®Algoliaã®Podcastã§ã™ğŸ”
description_long: æ¯é€±1å›ã€æ—¥æœ¬ã§åƒãAlgoliaã®ãƒ¡ãƒ³ãƒãƒ¼ã‚’ä¸­å¿ƒã«ãŠå±Šã‘ã—ã¾ã™ã€‚
email: eiji@algolia.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: AlgoliaJP
itunes_podcast_url:
keywords: algolia,search,saas
language: ja
markdown: kramdown
permalink: /:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Algolia Podcast
url: https://algolia.com
